[phases.setup]
nixPkgs = ['...', 'bun'] # Inclui Bun no ambiente

[phases.install]
cmds = ['bun install'] # Substitui npm i por bun install

[phases.build]
cmds = ['bun --filter client run build', 'bun --filter server run build'] # Compila client e server

[phases.start]
cmds = ['bun server/index.ts'] # Inicia o servidor